### ISSUE TITLE
ClimaconCharacter change with Language

### ISSUE THREAD

**Issue by authiatr** [comyarzaheri/CZWeatherKit#12]
Hi,

The ClimaconCharacter isn't the same when you change the language for the same city. 
For example:
When I set the language to english, the ClimaconCharacter is '$'. But in French for the same city and the same time, the ClimaconCharacter is 'I'. But the summary is translate well.
![bug](https://cloud.githubusercontent.com/assets/10559183/5773904/2837a726-9d68-11e4-9ad3-4d02fb09ce61.png)

Best regards

**Comment by comyarzaheri** [comment]
Interesting, which weather service are you using? I'll look into it and see if I can figure out what's happening.

**Comment by authiatr** [comment]
I'm using CZOpenWeatherMapService. 
Oh ok I get it! If you can solve it it'll be nice :)
Thank you for your answer.
Have a good one.

**Comment by souhl** [comment]
Hi,

for OWM it would be better to use the Icon information provided by the API instead using the description.
OWM provides an information on the icon as part of the JSON reply. This is language independent and even more important icon and weather description are not always equal. So, weather can be "rain" and icon may show rain and sun.

Sascha

**Comment by comyarzaheri** [comment]
@souhl  Yeah that was my thinking as well, I just haven't had time to do it. I'd be happy to merge a pull request if you end up implementing it on your own.

**Comment by souhl** [comment]
@comyarzaheri I just replaced/added this function:
For "debugging" I am using the compass symbol in the case the icon is not mapped.
Can upload that later next week. Not so much time right now...

- (Climacon)climaconCharacterForIcon:(NSString *)description
{

    Climacon icon = ClimaconSun;
    
    if ([description isEqualToString:@"01d"])
    {
        icon = ClimaconSun;
    } else if ([description isEqualToString:@"02d"])
    {
        icon = ClimaconCloudSun;
    }else if ([description isEqualToString:@"03d"])
    {
        icon = ClimaconCloud;
    } else if ([description isEqualToString:@"04d"])
    {
        icon = ClimaconCloud;
    } else if ([description isEqualToString:@"09d"])
    {
        icon = ClimaconRain;
    } else if ([description isEqualToString:@"10d"])
    {
        icon = ClimaconRainSun;
    } else if ([description isEqualToString:@"11d"])
    {
        icon = ClimaconLightning;
    } else if ([description isEqualToString:@"13d"])
    {
        icon = ClimaconSnow;
    } else if ([description isEqualToString:@"50d"])
    {
        icon = ClimaconFog;
    } else if ([description isEqualToString:@"01n"])
    {
        icon = ClimaconMoon;
    } else if ([description isEqualToString:@"02n"])
    {
        icon = ClimaconCloudMoon;
    } else if ([description isEqualToString:@"03n"])
    {
        icon = ClimaconCloud;
    } else if ([description isEqualToString:@"04n"])
    {
        icon = ClimaconCloud;
    } else if ([description isEqualToString:@"09n"])
    {
        icon = ClimaconRain;
    } else if ([description isEqualToString:@"10n"])
    {
        icon = ClimaconRainMoon;
    } else if ([description isEqualToString:@"11n"])
    {
        icon = ClimaconLightning;
    } else if ([description isEqualToString:@"13n"])
    {
        icon = ClimaconSnow;
    } else if ([description isEqualToString:@"50n"])
    {
        icon = ClimaconFog;
    } else
    {
        icon = ClimaconCompass;
    }
    
    return icon;
}

**Comment by comyarzaheri** [comment]
I believe this is resolved in the new release, so I'll go ahead and close this issue. Feel free to reopen it if you find any issues. Thanks.
