### ISSUE TITLE
CZWeatherKit does not support historical data

### ISSUE THREAD

**Issue by quicklywilliam** [comyarzaheri/CZWeatherKit#14]
Would love to see CZWeatherKit support querying historical weather data (cf http://openweathermap.org/history). I may add this for my own purposes if it is not already planned…

**Comment by comyarzaheri** [comment]
I wasn't planning on adding it. If you do pursue it on your own, I'd appreciate the pull request!

**Comment by comyarzaheri** [comment]
@quicklywilliam Just wanted to let you know that I'm currently working on adding this.

**Comment by comyarzaheri** [comment]
I've added support for this in the new release, any feedback is appreciated. Thanks.

**Comment by quicklywilliam** [comment]
Nice! Will check it out.
