### ISSUE TITLE
Problem with WatchKit integration

### ISSUE THREAD

**Issue by souhl** [comyarzaheri/CZWeatherKit#15]
Hi,

may be you have an idea...
I want to add WatchKit support to my app. But when I integrate CZWeatherKit and compile I get the the following errors:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_CZOpenWeatherMapService", referenced from:
      objc-class-ref in SensorViewController.o
  "_OBJC_CLASS_$_CZWeatherLocation", referenced from:
      objc-class-ref in SensorViewController.o
  "_OBJC_CLASS_$_CZWeatherRequest", referenced from:
      objc-class-ref in SensorViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Thanks
Sascha

**Comment by comyarzaheri** [comment]
Hmm, that's odd. Are you using Cocoa Pods?

**Comment by souhl** [comment]
Solved it by adding the CZWeather files to the build phase.
