### ISSUE TITLE
CZOpenWeatherMapRequest with location

### ISSUE THREAD

**Issue by paulgee31** [comyarzaheri/CZWeatherKit#18]
When using CZopenWeatherMapRequest with LocationFromCoordinate the API URL is incorrectly formatted 
http://api.openweathermap.org/data/2.5/weather?lat=51.2758,lon=-0.7763&lang=en&mode=json&APPID=XXXXX
The lat and lon should be separated by an & not a ,

I think the problem is componentForLocation in CZopenWeatherMapAPI

**Comment by comyarzaheri** [comment]
Good catch, figured something was bound to be broken with the update. I'll have a fix out ASAP.

**Comment by comyarzaheri** [comment]
Alright, I've pushed out [release 2.0.1](https://github.com/comyarzaheri/CZWeatherKit/releases/tag/2.0.1) with the fix for this. Thanks for reporting!

**Comment by paulgee31** [comment]
Thanks for the quick turn around and a great API.
