### ISSUE TITLE
windspeed missing in the CurrentForecastCondition

### ISSUE THREAD

**Issue by souhl** [comyarzaheri/CZWeatherKit#19]
Hi,

why the windspeed is not available in the Forecast any longer?

Sascha

**Comment by comyarzaheri** [comment]
In this case, it was more a matter of it not being consistently being provided across the APIs. I think I'll add this, but I probably won't prioritize it (currently working on finishing my caching library so I can add it to CZWeatherKit).

**Comment by comyarzaheri** [comment]
I've created issue #21 to address this.

**Comment by souhl** [comment]
Okay, in this case we will add it on our own, as we use it in the current version of our app...
