### ISSUE TITLE
low and high temperature missing in Current Weather

### ISSUE THREAD

**Issue by souhl** [comyarzaheri/CZWeatherKit#20]
Hi,

why high and low temp and station ID are missing now in current weather information?

Thanks
Sascha

**Comment by comyarzaheri** [comment]
Was station ID ever present? As for high and low temperatures, my reasoning for it is that the "current" weather doesn't have a high or a low, right? It's an instantaneous snapshot so only the current temperature make sense to include. Also it's not consistently provided across the different APIs.

However, I'm open to the idea of adding it if there seems to be enough need for it.

**Comment by souhl** [comment]
May be I added station ID on my own. This was helpful for us during testing as OWM wasn't always very reliable. Low and high are usual things to display. And you are right, min/max are actually not available. We use this value from the forecast data of OWM. Because of this we get the forecast data for the current day, too, to show all the relevant data.
