### ISSUE TITLE
days property's value becomes 0 after CZWeatherRequest is copied

### ISSUE THREAD

**Issue by alperg9** [comyarzaheri/CZWeatherKit#23]
I was getting only 4 days of forecast no matter what i typed inside this method: CZOpenWeatherMapRequest.newDailyForecastRequestForDays(7)

I noticed in  CZWeatherRequest class // dispatchWithAPI method the [self copy] only retains feature string.

**Comment by comyarzaheri** [comment]
You're right, this is a bug. I'll try to get this fixed ASAP and push out another release.

**Comment by comyarzaheri** [comment]
v2.0.2 has been published. All request objects properly implement NSCopying now, thanks for reporting!

**Comment by alperg9** [comment]
No problem :) Thanks for the prompt response!
