### ISSUE TITLE
Shouldn't it be CZOpenWeatherMapRequest in your example

### ISSUE THREAD

**Issue by souhl** [comyarzaheri/CZWeatherKit#24]
Hi,

shouldn't 

CZOpenWeatherMap *request = [CZOpenWeatherMap newCurrentRequest];
request.location = [CZWeatherLocation locationForCity:@"Seattle" state:@"WA"];
[request sendWithCompletion:^(CZWeatherData *data, NSError *error) {
    CZWeatherCurrentCondition *condition = date.current;
    // dreams come true here
}];

look like this?

CZOpenWeatherMapRequest *request = [CZOpenWeatherMapRequest newCurrentRequest];
request.location = [CZWeatherLocation locationForCity:@"Seattle" state:@"WA"];
[request sendWithCompletion:^(CZWeatherData *data, NSError *error) {
    CZWeatherCurrentCondition *condition = date.current;
    // dreams come true here
}];

and "date.current", should be "data.current" I guess..

Sascha

**Comment by comyarzaheri** [comment]
Yeah you're right, fixing...
