### ISSUE TITLE
Duplicate case value: 'ClimaconFahrenheit' and 'ClimaconShowers' both equal '39'

### ISSUE THREAD

**Issue by iwheelbuy** [comyarzaheri/CZWeatherKit#28]
Duplicate case value: 'ClimaconFahrenheit' and 'ClimaconShowers' both equal '39'

ClimaconFahrenheit              = '\'',
ClimaconShowers                 = '\'',

**Comment by comyarzaheri** [comment]
Release [2.2.1](https://github.com/comyarzaheri/CZWeatherKit/releases/tag/2.2.1) fixes this. Thanks for reporting!

**Comment by iwheelbuy** [comment]
Thank you for such a great weather kit
