### ISSUE TITLE
Climacons not displaying in UILabel

### ISSUE THREAD

**Issue by MadeByDouglas** [comyarzaheri/CZWeatherKit#36]
I tried following the example on the cocoapods page as well as general advice on custom fonts and iOS etc, but no dice. It just shows the char mapped to the climacon, not the actual icon. See http://stackoverflow.com/questions/37199314/getting-climacons-to-display-in-uilabel-with-czweatherkit-in-swift

**Comment by comyarzaheri** [comment]
Can you check if the font file is included under `Copy Bundle Resources` under `Build Phases`?

**Comment by MadeByDouglas** [comment]
yeah thats this right?
![screen shot 2016-05-12 at 5 53 05 pm](https://cloud.githubusercontent.com/assets/10858053/15234824/92ad41c8-186a-11e6-91fc-5964d62653fd.png)

and I use this snippet to make sure to get the right name of the actual font, 

`for family: String in UIFont.familyNames()
        {
            print("\(family)")
            for names: String in UIFont.fontNamesForFamilyName(family)
            {
                print("== \(names)")
            }
        }`

which gives me 
Climacons-Font
== Climacons-Font

and it shows in IB as well

**Comment by comyarzaheri** [comment]
Yeah, that's it. Well it looks like it's included, that was my main guess...

The really odd part is you're seeing the Climacons font in IB, so it means your Info.plist is setup correctly. From the stackoverflow, it looks like you've tried setting the font both in IB and programmatically on the main queue..both of those should have worked. Honestly I'm kind of stumped...maybe the font file itself is corrupt (unlikely but maybe)? Can you try using this [font file](https://github.com/comyarzaheri/Sol/blob/master/Sol/Sol/Resources/Fonts/Climacons.ttf)? I just made a test project using this and didn't have any issues. Let me know how that goes.

**Comment by MadeByDouglas** [comment]
Ok, well at least goo to know I'm not the only one perplexed haha. I've been going crazy trying to figure this out. I will try that font file as I was starting to wonder something similar

**Comment by MadeByDouglas** [comment]
Hooray! that was it. Ok it works now. And makes sense now that I think about it, with the other one would not work in Pages either. If i highlight a character in Font Book to see what it is OS X would just have a ? inside a square. With the one you sent me, it shows the char, D, " !, etc.

**Comment by MadeByDouglas** [comment]
Well thanks I appreciate you taking a look and providing a good font file. I got mine from some github repo, I should have tried another sooner.

**Comment by comyarzaheri** [comment]
Awesome, glad it worked!
